language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_install:
  - sudo add-apt-repository universe
  - sudo apt-get -qq update
  - sudo apt-get install -y libopus-dev libsodium-dev
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
